// Auto-generated by zoop-codegen
// DO NOT EDIT - changes will be overwritten
//
// This file was generated from the source file with the same name.
// Class definitions have been enhanced with:
//   - Inherited methods from parent classes
//   - Property getters and setters
//   - Optimized field layouts

const std = @import("std");
pub const SimpleClass = struct {
    allocator: std.mem.Allocator,

    pub fn init(allocator: std.mem.Allocator) SimpleClass {
        return .{
            .allocator = allocator,
        };
    }
    pub fn deinit(self: *SimpleClass) void {
        _ = self;
    }
};

