// Auto-generated by zoop-codegen
// DO NOT EDIT - changes will be overwritten
//
// This file was generated from the source file with the same name.
// Class definitions have been enhanced with:
//   - Inherited methods from parent classes
//   - Property getters and setters
//   - Optimized field layouts

const std = @import("std");
pub const InlineFnClass = struct {
    value: u32,

    pub fn init(value: u32) InlineFnClass {
        return .{ .value = value };
    }
    pub inline fn getValue(self: *const InlineFnClass) u32 {
        return self.value;
    }
    pub inline fn get_encoding(_: *const InlineFnClass) []const u8 {
        return "utf-8";
    }
};

