// Auto-generated by zoop-codegen
// DO NOT EDIT - changes will be overwritten
//
// This file was generated from the source file with the same name.
// Class definitions have been enhanced with:
//   - Inherited methods from parent classes
//   - Property getters and setters
//   - Optimized field layouts

const std = @import("std");
pub const StringMixin = struct {
    encoding: []const u8,
    pub inline fn get_encoding(self: *const @This()) []const u8 {
        return self.encoding;
    }
};

pub const TextEncoder = struct {
    encoding: []const u8,

    allocator: std.mem.Allocator,

    pub fn init(allocator: std.mem.Allocator) TextEncoder {
        return .{
            .allocator = allocator,
            .encoding = "utf-8",
        };
    }

};

